-- Side Quests schema for Supabase/Postgres
-- Apply in Supabase SQL editor.

create table if not exists public.side_quests (
  quest_id bigint generated by default as identity primary key,
  tag text,
  title text not null,
  description text not null,
  task text,
  reward_xp integer not null default 100,
  difficulty text not null default 'medium' check (difficulty in ('easy', 'medium', 'hard')),
  programming_language_id bigint not null references public.programming_languages(id) on delete restrict,
  starter_code text not null default '',
  test_cases jsonb not null default '[]'::jsonb,
  solution_code text not null default '',
  min_xp_required integer not null default 0,
  starts_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '14 day'),
  is_active boolean not null default true,
  created_by bigint references public.users(user_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_side_quests_active_window
  on public.side_quests (is_active, starts_at, expires_at);

create index if not exists idx_side_quests_language
  on public.side_quests (programming_language_id);

create index if not exists idx_side_quests_tag
  on public.side_quests (tag);

create unique index if not exists uq_side_quests_language_tag
  on public.side_quests (programming_language_id, lower(tag))
  where tag is not null;

create table if not exists public.user_side_quests (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(user_id) on delete cascade,
  quest_id bigint not null references public.side_quests(quest_id) on delete cascade,
  status text not null default 'in_progress' check (status in ('in_progress', 'completed')),
  completed_at timestamptz,
  xp_awarded integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_side_quests_user_id_quest_id_unique unique (user_id, quest_id)
);

create index if not exists idx_user_side_quests_user
  on public.user_side_quests (user_id);

create index if not exists idx_user_side_quests_status
  on public.user_side_quests (user_id, status);

create index if not exists idx_user_side_quests_quest
  on public.user_side_quests (quest_id);

alter table public.side_quests
  add column if not exists tag text;
